config/routes.rb
Rails.application.routes.draw do

#  devise_for :admins

  devise_for :admin, controllers: {
  passwords: 'admin/passwords',
  registrations: 'admin/registrations',
  sessions: 'admin/sessions'
 }

  root 'public/homes#top'
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
 }

  namespace :admin do
    root :to => 'homes#top'
    #patch '/genres' => 'genres#update'
    resources :items
    resources :genres,only:[:index,:edit,:create,:update]
    resources :customers
    resources :orders,only:[:index,:show,:update]
    resources :order_details, only:[:update]
  end
  namespace :public do
    get '/customers/my_page' => 'customers#show'
    get '/about' => 'homes#about'
    get '/customers/unsubcribe' => 'customers#unsubcribe'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :items, only:[:index,:show,:new] do
    get :search, on: :collection
    patch '/update' => 'customers#update'
    end

    root 'items#top'
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
    resources :cart_items
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    resources :orders, only:[:new,:create,:index,:show]
    resource :customers, only:[:edit,:update]
    resources :addresses, only:[:index, :edit, :destroy, :create, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name,  presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   validates :amount, presence: true
   belongs_to :customer
   belongs_to :item
   
   def subtotal
    item.with_tax_price * amount
   end

   def self.aggregate(column)
    self.all.map { |cart_item| cart_item.item[column] }.sum
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :telephone_number, presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  attachment :image
  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
  
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many   :order_details, dependent: :destroy
	enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "製作不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @Items = Item.page(params[:page]).per(10)
    @orders = Order.all
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
end

def update
		order = Order.find(params[:id])
		@order_details = order.order_details
    order.update(order_params)
    redirect_to admin_order_path(order.id)
end


private

def order_params
  params.require(:order).permit(:name, :address, :total_payment, :customer_id, :postal_code, :shipping_cost, :payment_method, :status, :created_at, :update_at)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    	before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
        when Admin
          admin_root_path
        when Customer
          public_items_path
      end
    end




	protected

	def configure_permitted_parameters
		added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :password, :password_confirmation ]

		devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/sessions_helper.rb
module Customer::SessionsHelper
end

app/views/admin/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <h10 style="background-color: #d3d3d3">注文履歴詳細</h10>
  </div>

  <div class="row mt-3">
    <div class="col-sm-9">
      <table class="table table-borderless">

        <tbody>
          <tr>
            <td>購入者</td>
            <td>
              <%= @order.customer.last_name %>
              <%= @order.customer.first_name %>
            </td>
          </tr>

          <tr>
            <td>注文日</td>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>

          <tr>
            <td>配送先</td>
            <td><%= @order.postal_code %><br>
                <%= @order.address %><br>
                <%= @order.name %>
            </td>
          </tr>

          <tr>
            <td>支払方法</td>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
        </tbody>

      </table>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-sm-9">

      <table class="table table-hover">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <% @order_details.each do |order_detail| %>
          <tbody>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= (order_detail.item.price * 1.1).floor %></td>
              <td><%= order_detail.amount %></td>
              <td><%= (order_detail.item.price * order_detail.amount * 1.1).floor %></td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f| %>
                  <%= f.select :making_status, [["着手不可", "着手不可"], ["製作待ち","製作待ち"], ["製作中","製作中"], ["製作完了","製作完了"]] %>
                  <%= f.submit "更新", class: "btn btn-primary btn-sm ml-3" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>

    <div class="col-sm-3 d-flex">
      <table class="table table-borderless align-self-end">
        <tbody>
          <tr class="border-bottom border-dark">
            <td>商品合計</td>
            <td><%= (@order.total_payment).floor.to_s(:delimited, delimiter: ',') %></td>
          </tr>

          <tr class="border-bottom border-dark">
            <td>送料</td>
            <td><%= @order.shipping_cost %></td>
          </tr>

          <tr class="border-bottom border-dark">
            <td>請求合計金額</td>
            <td><%= @order.total_payment+@order.shipping_cost %></td>
          </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>