config/routes.rb
Rails.application.routes.draw do

#  devise_for :admins

  devise_for :admin, controllers: {
  passwords: 'admin/passwords',
  registrations: 'admin/registrations',
  sessions: 'admin/sessions'
 }

  root 'public/homes#top'
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
 }

  namespace :admin do
    root :to => 'homes#top'
    #patch '/genres' => 'genres#update'
    resources :items
    resources :genres,only:[:index,:edit,:create,:update]
    resources :customers
    resources :orders,only:[:index,:show,:update]
    resources :order_details, only:[:update]
  end
  namespace :public do
    get '/customers/my_page' => 'customers#show'
    get '/about' => 'homes#about'
    get '/customers/unsubcribe' => 'customers#unsubcribe'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :items, only:[:index,:show,:new] do
    get :search, on: :collection
    patch '/update' => 'customers#update'
    end

    root 'items#top'
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
    resources :cart_items
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    resources :orders, only:[:new,:create,:index,:show]
    resource :customers, only:[:edit,:update]
    resources :addresses, only:[:index, :edit, :destroy, :create, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name,  presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   validates :amount, presence: true
   belongs_to :customer
   belongs_to :item
   
   def subtotal
    item.with_tax_price * amount
   end

   def self.aggregate(column)
    self.all.map { |cart_item| cart_item.item[column] }.sum
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :telephone_number, presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  attachment :image
  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
  
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many   :order_details, dependent: :destroy
	enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "製作不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_created_error] = "ジャンル名を入力してください。"
      redirect_to admin_genres_path
    end
  end

  def edit
  @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      flash[:genre_updated_error] = "ジャンル名を入力してください"
      redirect_to edit_admin_genre_path
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    	before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
        when Admin
          admin_root_path
        when Customer
          public_items_path
      end
    end




	protected

	def configure_permitted_parameters
		added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :password, :password_confirmation ]

		devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/sessions_helper.rb
module Customer::SessionsHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h10 style="background-color: #d3d3d3">ジャンル編集</h10>
        <div class="row d-flex justify-content-center">
          <% if flash[:genre_created_error] %>
          <span class="text-danger"><%= flash[:genre_created_error] %></span>
          <% end %>
        </div>


      <%= form_with model: @genre, url: admin_genre_path do |f| %>
        <div class="form-group">
         <strong>ジャンル名</strong> <%= f.text_field :name, class: "form-control" %>         <%= f.submit "変更を保存", class: "btn btn-success mt-3 mx-auto" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h10 style="background-color: #d3d3d3">ジャンル一覧・追加</h10>

        <div class="col-md-8">
          <strong>ジャンル名</strong>


        <div class="row d-flex justify-content-center">
          <% if flash[:genre_created_error] %>
            <span class="text-danger"><%= flash[:genre_created_error] %></span>
          <% end %>
        </div>

      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control" %>         <%= f.submit "新規登録", class: "btn btn-success mt-3 mx-auto" %>
        </div>


        </div>
      <% end %>
    </div>
    </div>
    <table class="table table-hover text-center">
      <thead>
        <tr>
          <th>ジャンル名</th>
        </tr>
      </thead>

      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>