config/routes.rb
Rails.application.routes.draw do

#  devise_for :admins

  devise_for :admin, controllers: {
  passwords: 'admin/passwords',
  registrations: 'admin/registrations',
  sessions: 'admin/sessions'
 }

  root 'public/homes#top'
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
 }

  namespace :admin do
    root :to => 'homes#top'
    #patch '/genres' => 'genres#update'
    resources :items
    resources :genres,only:[:index,:edit,:create,:update]
    resources :customers
    resources :orders,only:[:index,:show,:update]
    resources :order_details, only:[:update]
  end
  namespace :public do
    get '/customers/my_page' => 'customers#show'
    get '/about' => 'homes#about'
    get '/customers/unsubcribe' => 'customers#unsubcribe'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :items, only:[:index,:show,:new] do
    get :search, on: :collection
    patch '/update' => 'customers#update'
    end

    root 'items#top'
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
    resources :cart_items
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    resources :orders, only:[:new,:create,:index,:show]
    resource :customers, only:[:edit,:update]
    resources :addresses, only:[:index, :edit, :destroy, :create, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name,  presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   validates :amount, presence: true
   belongs_to :customer
   belongs_to :item
   
   def subtotal
    item.with_tax_price * amount
   end

   def self.aggregate(column)
    self.all.map { |cart_item| cart_item.item[column] }.sum
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :telephone_number, presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  attachment :image
  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
  
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many   :order_details, dependent: :destroy
	enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "製作不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    	before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
        when Admin
          admin_root_path
        when Customer
          public_items_path
      end
    end




	protected

	def configure_permitted_parameters
		added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :password, :password_confirmation ]

		devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/sessions_helper.rb
module Customer::SessionsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="text-success">ながのケーキ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f97bdf8bf2.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div id="wrapper">

        <header>
          <nav class="navbar navbar-expand-lg">
           <div class="container">
              <%= link_to root_path do %>
              <%= image_tag "top.jpeg", size: '240x180' %>
              <% end %>

              <ul class="nav navbar-nav navbar-right">

                <% if customer_signed_in? %>

                <li style="font-family: HiraMinPro-W6; margin-top: 15px;">
                ようこそ、<%= current_customer.last_name  %>さん！
                </li>

                <li>
                <%= link_to public_customers_my_page_path, class: "fas btn btn-light" do %>
                マイページ
                <% end %>
                </li>

                <li>
                <%= link_to public_items_path, class: "fas btn btn-light" do %>
                商品一覧
                <% end %>
                </li>

                <li>
                <%= link_to public_cart_items_path, class: "fas btn btn-light" do %>
                カート
                <% end %>
                </li>

                <li>
                <%= link_to destroy_customer_session_path, method: :delete, class: "fas btn btn-light" do %>
                ログアウト
                <% end %>
                </li>

                <% elsif admin_signed_in? %>

                <li>
                <%= link_to admin_items_path, class: "fas btn btn-light" do %>
                商品一覧
                <% end %>
                </li>

                <li>
                <%= link_to admin_customers_path, class: "fas btn btn-light" do %>
                会員一覧
                <% end %>
                </li>

                <li>
                <%= link_to admin_root_path, class: "fas btn btn-light" do %>
                注文履歴一覧
                <% end %>
                </li>

                <li>
                <%= link_to admin_genres_path, class: "fas btn btn-light" do %>
                ジャンル一覧
                <% end %>
                </li>

                <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: "fas btn btn-light" do %>
                ログアウト
                <% end %>
                </li>

               <% else %>

                <li>
                <%= link_to public_about_path, class: "fas btn btn-light" do %>
                About
                <% end %>
                </li>

                <li>
                <%= link_to public_items_path, class: "fas btn btn-light" do %>
                商品一覧
                <% end %>
                </li>

                <li>
                  <%= link_to new_customer_registration_path, class: "fas btn btn-light" do %>
                  新規登録
                  <% end %>
                </li>

                <li>
                  <%= link_to new_customer_session_path, class: "fas btn btn-light" do %>
                  ログイン
                  <% end %>
                </li>
              <% end %>
              </ul>
          </div>
          </nav>
        </header>

        <main id="content">
          <%= yield %>
        </main>
    </div>
  </body>
</html>